server:
  port: 8082
feign:
  okhttp:
    enabled: true # ??OKHttp?????
hm:
  swagger:
    title: ?????????
    package: com.hmall.cart.controller
  db:
    database: hm-cart


# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
